development:
  adapter: postgresql
  encoding: unicode
  database: basecampdev 
  pool: 5
  username: apprentice
  password:
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: basecamptest 
  pool: 5
  username: apprentice
  password:
  host: localhost
  port: 5432
